### ISSUE TITLE
Upgrade to socket.io 1.0

### ISSUE THREAD

**Issue by vojtajina** [karma-runner/karma#1220]

**Comment by mzgol** [comment]
Just commenting for subscribers to this issue that this affects BrowserStack stability. I've reported #1284 not noticing this one.

**Comment by juliemr** [comment]
This also seems to affect BrowserStack stability outside of OS X - see errors on the angular Travis CI such as https://travis-ci.org/angular/angular.js/jobs/48153879

**Comment by sindresorhus** [comment]
Because Karma is using the very outdated Socket.io users have to download a [*8 MB* useless file](https://github.com/qfox/ZeParser/blob/805f5441e7cf2b3bc84b07c05eed6cc1f198872a/benchmark.html) (karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/active-x-obfuscator/node_modules/zeparser/benchmark.html), which is not apparent in later Socket.io versions... Please update.

**Comment by Dignifiedquire** [comment]
@everyone around here, There is working version with the latest socket.io in this PR #1404 But I need some real world tests to be sure it works, so please go ahead and try it out and report bugs :bomb:

**Comment by mzgol** [comment]
What has happened? Karma `0.12.33` includes socket.io `0.9.16` whereas the previous `0.12.32` included socket.io `1.3.5`... old bugs are back :confused:

**Comment by Dignifiedquire** [comment]
karma@0.12.32 was an accidental release, which released the canary version into the stable branch, which it shouldn't have (that's why there is no tag of it on github or anything like that..) 
`0.12.33` was the first release to actually mirror what is on master on github. 
I'm going to merge the socket.io upgrade into canary today, so that way we `0.13.0-rc.1` should have the latest socket.io and as soon as I've fixed all the integration test issues I want to pull this into stable.

**Comment by Dignifiedquire** [comment]
Also, I'm very sorry for all this chaos @mzgol :(

**Comment by mzgol** [comment]
Thanks for the info, @Dignifiedquire; I didn't know Karma 0.12.32 was not released from `master`.

**Comment by Dignifiedquire** [comment]
I just published `0.13.0-rc.1` it has the latest socket.io version, please take it for a spin and report all the bugs

**Comment by mzgol** [comment]
@Dignifiedquire I can't currently test this version as `grunt-karma` declares a karma `peerDependency` at `~0.12.0` which prevents it from even installing.

**Comment by Dignifiedquire** [comment]
:cry: I hate peer dependencies..

**Comment by necramirez** [comment]
Hi!  I'd like to suggest to change the dependency on `socket.io` to NOT be a specific version.  Right now, `package.json` specifies it to be EXACTLY `0.9.16`:  https://github.com/karma-runner/karma/blob/v0.12.36/package.json#L211

However, `socket.io` has no such release https://github.com/Automattic/socket.io/releases/tag/0.9.16 (maybe they accidentally deleted it?).  Browsing the `socket.io` releases list, after `0.9.15`, it skips `0.9.16`, but there is a `0.9.17`.

I think this should be fixed immediately, before even the upgrade to `socket.io` 1.x.

**Comment by Dignifiedquire** [comment]
This is already fixed in the canary branch: https://github.com/karma-runner/karma/blob/canary/package.json#L214

**Comment by necramirez** [comment]
I was suggesting that there be a hotfix, since `master` is currently broken, and I don't know how soon the next release will be.

Unless there will be a release in the next couple of days?
