### ISSUE TITLE
Scrolling Events

### ISSUE THREAD

**Issue by kand** [karma-runner/karma#1374]
I'm unable to test scrolling events via changing scrollTop, scrollTop will always come out as 0. I believe this was covered and incorrectly closed in ticket: [#345](https://github.com/karma-runner/karma/issues/345).

**Comment by Dignifiedquire** [comment]
Can you please provide some more details, about what exactly is not working, and optimally a small repro setup?

**Comment by hydhaval** [comment]
I am also facing the same issue. When I add "window.scrollTo(100, 400);" PhantomJS always returns 0. However this works fine while I switch to Chrome.

**Comment by hydhaval** [comment]
@kand did you find any solution with this?

**Comment by hydhaval** [comment]
@Dignifiedquire I am on the same boat as @kand let me know if I can provide any details.

**Comment by kand** [comment]
Unfortunately, I just ended up using Chrome instead. The ticket I referenced goes over basically the exact same issue I was having.

**Comment by hydhaval** [comment]
@kand yeah in my case, using chrome is not a option.

**Comment by wesleycho** [comment]
This sounds like a potential PhantomJS issue. This doesn't sound like the responsibility of karma.

This sounds like a relevant piece of information though: https://github.com/ariya/phantomjs/issues/10162 .

FWIW, I want to create support for headless Chrome/Chromium, so that should probably address this problem once that is done.

**Comment by devoto13** [comment]
Closing as per above. PhantomJS is archived and it is better option to use headless Chrome or Firefox now.
