### ISSUE TITLE
Add option to execute Browsers in serial instead of parallel

### ISSUE THREAD

**Issue by ghost** [karma-runner/karma#1465]
Can it  change to run one by one?

thanks

**Comment by Dignifiedquire** [comment]
You can use a task runner like gulp or grunt to trigger different runs one after another by using different configurations.

**Comment by Dignifiedquire** [comment]
For questions and support please use the mailing list or Gitter. The issue tracker is for bug reports and feature discussions only.

**Comment by jokeyrhyme** [comment]
I'm having this problem as well. I'm using the following karma plugin to automatically launch browsers that are present without causing errors for missing browsers:
- https://github.com/litixsoft/karma-detect-browsers

If every member of my team had all the same browsers installed, then it would be feasible to modify our grunt / gulp configuration to execute different nearly-identical configurations to get tests running in one browser at a time. Unfortunately, my team members are spread across Linux, Windows and OS X, so the only way to eliminate the automatic detection problem is to only ever test in PhantomJS, Chrome and Firefox and never test in Safari or Internet Explorer, or the various smartphone emulators.

So, automatic browser detection is necessary for my team, and this is not built-in to Karma: #1470.

The other problem my team has is that we do not all run the same hardware: some have more RAM, some have faster CPUs. Because of this, there is great variation in our ability to run tests in every single detected browser all at the same time. Even on the fastest machines we do not have a 100% pass rate (whilst we do when manually triggering the tests in one browser at a time).

Ultimately, the gulp / grunt suggestion here doesn't apply to our use case, so it would still be extremely helpful if karma has a built-in option to launch / capture browsers in serial instead of in parallel. I suspect this would help greatly with Travis CI as well.

**Comment by rshah88** [comment]
This feature would also help in performance tests as currently when running performance tests.
Currently when I run the performance numbers with all browsers the numbers are 5-6 times compared to when the test is run on individual browser.
