### ISSUE TITLE
Browser test script injection and navigation testing

### ISSUE THREAD

**Issue by robertleeplummerjr** [karma-runner/karma#1582]
Let me first state this may already be in place but I couldn't find it after 3 hours of google-ing.  Also, I may be speaking out of naivety, but It would be very very nice to:
- dynamically insert tests into the browser for high level testing
- hijack XMLHttpRequest listening for all ajax to complete
- invoke and detect navigation

Say I would like to test:
multi directive/component navigation
success of a set of actions on a page
test forms & services for proper & improper input

The majority of testing I see abstracts these items into an object where the object does all the controlling, however we still see these problems creep up, and are generally "seen" rather than detected.  If I create a form that is specific to the options above, I'd create a test to reproduce the actions from the client and this could avoid problems that are not being tested.
Also:  The browser can only handle about 300-500 items for smooth transitions/animation, and less than 1000-5000 before it feels terribly clunky.  If we use the standard paradigm, pages will ALWAYS feel clunky when large.  However, if you keep the number of elements low, and reuse them, the page will nearly ALWAYS feel fast and light, even if there are a ridiculous amount of objects managing those elements (see http://robertleeplummerjr.github.io/megaTable.js/ , DO NOT visit if you are epileptic.. seriously).  You are probably asking yourself: "What does that have to do with...?"  If we use the standard paradigm pages don't scale, and thus the abstractions are bound directly to objects (arguably), if we simply test the UI and browser interaction using the above methods, abstractions can be simplified and there will be less time used in developing abstraction and more time knowing what does and doesn't work on our site.
In the end, css can conflict with the abstractions, and thus the whole argument above snowballs in both importance and necessity.

The question:  Do these test methods exist?  If they do, where are they?  If they do not, I would like to work with my employer and write them.  I would also like karma team input because I feel this is a relatively untested part of the web that would be ideally tested.

**Comment by Dignifiedquire** [comment]
Thanks for the detailed description, I'll try and give you understandable answers as much as I can.

> dynamically insert tests into the browser for high level testing

I'm not entirely sure what you mean with this. At the moment karma does pretty much this, just that this is not exposed to the end user. When a browser window is opened and karma connects to it, it creates an iframe and loads all tests via ajax requests and then executes them inside the iframe.

> hijack XMLHttpRequest listening for all ajax to complete

This is not provided per se by karma, but should be doable with something like [sinon.js](http://sinonjs.org/) as far as I understand.

> invoke and detect navigation

This is the problematic part. Because karma relies on other test frameworks like mocha, jasmine and qunit to do the actual testing part, we are restricted here. These frameworks were written a long time ago and assumed to be a simple script executing on one page with no server backend. So as soon as you navigate away from the page your test runs break, as the old state is unknown in the new page. For that reason karma detects all attempts of leaving the page and fails the test run, as there is no "good" outcome with this action.
I would love to find a solution for this, as it is quite restricting in some areas, especially if you want to test things like the `history` api, or page navigation. But I haven't seen a good solution yet, that does not entail using sth like selenium.

**Comment by robertleeplummerjr** [comment]
behold: http://robertleeplummerjr.github.io/kid-commander/
This test shows it is possible, but with a parent launcher.  Thoughts?

**Comment by robertleeplummerjr** [comment]
Since my last comment, I changed the name from "kid-commander" to "pri" or "Persistent Request Interceptor".  It can now detect the following on children windows:
* onBeforePageLoad
* onAllRequestsDone
* onClose
* any ajax request
Next is to add in some simple use case of open window, do some stuff, ensure it passes the test, close window.  I'm excited!

**Comment by robertleeplummerjr** [comment]
Also, I forgot to mention, it can persist when the window's dom location changes, which is pretty fantastic.  So now we can follow the navigation of a child page, wicked cool!

**Comment by devoto13** [comment]
I'm going to close this issue as it seems that the original issue has been resolved and the way Karma works was explained. Karma is primarily designed for running unit tests and hence some things should be mocked one way or another. If one needs to test complex interactions with the browser (tabs, navigations, etc), it is better to use one of the many frameworks for integration testing.
