### ISSUE TITLE
Crashing when running out of memory

### ISSUE THREAD

**Issue by ajbogh** [karma-runner/karma#1588]
I have an 8GB memory ultrabook (non-upgradable) that I use for development. When I have more than 6 tabs open in Chrome and attempt to run Karma unit tests, eventually memory will run out and Karma will cause the entire system, including the mouse and all applications, to grind to a halt, as if it's stuck in an endless loop. Eventually Karma may crash PhantomJS or it may crash the terminal, but sometimes it fails to do that and will hang for 15 minutes or more until I perform a hard reset on the system.

If I'm lucky I can move the mouse to the terminal and start hitting Ctrl-C repeatedly until it kills Karma. I've had to learn to close as many applications and tabs as possible while changing files.

Would it be possible to limit the processor usage of Karma to a few cores, not all, or to limit the memory usage so that it doesn't lock the computer when it gets stuck?

Karma version: 0.12.1

**Comment by ajbogh** [comment]
This issue happens more regularly when Karma server is already active in Webstorm and the developer runs it again from the command line.

**Comment by wawyed** [comment]
From what I've discerned. It would appear that the problem is related to the fact that karma doesn't stop/kill phantomjs after a test is run, so every time you re-run the test the memory usage of the browser keeps increasing until it crashes.

The workaround I found is in webstorm click the  Karma Server tab from your unit test run and then click the Stop Karma Server button to kill Karma and the browser so the memory can be freed.

Hope that helps.

**Comment by Dignifiedquire** [comment]
Karma is running in a node process, so it pretty much is not able to take up more than 1.5GB memory (don't quote me on that, you can look up v8 memory limit if you want to know the exact number). The culprit here is PhantomJS and there are a lot of issues over there where you can chime in, but the gist is that they don't plan on fixing the main issue, which is cleaning up the page memory on page reload. Which is the reason why a long running PhantomJS instance will eat your memory until it dies :(
