### ISSUE TITLE
Error running against multiple browsers in 0.13.12.

### ISSUE THREAD

**Issue by jgerigmeyer** [karma-runner/karma#1652]
Since upgrading to ``0.13.12``, I get an error (``Some of your tests did a full page reload!``) any time I try to run against multiple browsers, regardless of what I use for the new ``concurrency`` setting.

```bash
./node_modules/.bin/karma start --browsers PhantomJS2,Chrome
................................................................................
..................................
PhantomJS 2.0.0 (Mac OS X 0.0.0): Executed 114 of 114 SUCCESS (1.026 secs / 0.145 secs)
PhantomJS 2.0.0 (Mac OS X 0.0.0) ERROR
  Some of your tests did a full page reload!
PhantomJS 2.0.0 (Mac OS X 0.0.0): Executed 114 of 114 ERROR (1.042 secs / 0.145 secs)
................................................................................
..................................
Chrome 46.0.2490 (Mac OS X 10.11.1): Executed 114 of 114 SUCCESS (2.118 secs / 0.279 secs)
```

**Comment by FuzzySockets** [comment]
Refer to https://github.com/karma-runner/karma/pull/1655 for a fix in cases where iframe is configured to false.

**Comment by TheSavior** [comment]
We were struggling with this problem ourselves for the last few days and just came across this issue. Surprisingly Google didn't provide it in the search results. 

If anyone else is having problems with error messages of:

```
Some of your tests did a full page reload!
```
and is running multiple browsers, update Karma.

**Comment by TheSavior** [comment]
This is still a problem even on the current version. When running with Chrome and Firefox, we still get the full page reload error.

**Comment by FuzzySockets** [comment]
We solved the issue for us.  It turns out one of our tests were actually doing a full page reload from some module's run block further up in the stack.  For some reason once jasmine reached the "maximumSpecCallbackDepth," the setTimeout call was simply giving our tests enough time to complete the reload and fail.

We were asking the wrong question... "Why are these tests failing after a certain number of specs are reached?", versus, "Why are any of these tests able to pass at all?"  Updating to the latest version of jasmine ensured our tests failed properly EVERY time.

**Comment by TheSavior** [comment]
We are using Mocha and have seen this while only having a single, simple, totally unrelated test. We ran the test suite on CI 400 times with only chrome and never had the reload message. We added Firefox and saw the message within the first 40 builds.
