### ISSUE TITLE
Using 'window.__karma__.info()` API to send arbitrary objects to the server does not work

### ISSUE THREAD

**Issue by devanshah1** [karma-runner/karma#2192]
### Expected behavior

Expect the info emitter to be dispatched which is set in the reporter. The reporter is expected to write to console a message. Refer to: https://groups.google.com/forum/#!topic/karma-users/ShR96TcKm6Q
### Actual behavior

Nothing is written to the terminal/console.
### Enviroment Details
- Karma version (output of `karma --version`): Tried on "0.13.22" and "1.0.0"
- Relevant part of your `karma.config.js` file
  Refer to: https://github.com/devanshah1/sample/blob/master/karma.conf.js
### Steps to reproduce the behaviour
1. Clone Repo: https://github.com/devanshah1/sample
2. Run `bash npm install` in repo folder
3. Run `bash npm install src` in repo folder
4. Run `npm test` in repo folder
5. Now in the console you should see "info emitter was called and following is the object" printed if the info event was triggered

**Comment by devanshah1** [comment]
Any one have and idea?

**Comment by devanshah1** [comment]
@dignifiedquire Are you aware of any karma plugins which are using the window.__karma__.info API?

**Comment by dignifiedquire** [comment]
@devanshah1 I know of nothing that actually uses this api I'm afraid

**Comment by devanshah1** [comment]
@dignifiedquire Do you know of any other way to send arbitrary objects to the server from the client?

**Comment by devanshah1** [comment]
@dignifiedquire I started taking a look at this issues and had a quick question regarding it, in terms of how it should be used? When you call the window.__karma__.info() API would it be able to be picked up by any reporter that is registered. And Also would the API only work if where you are calling it from is part of a karma start function.

**Comment by devanshah1** [comment]
@dignifiedquire would you be able to provide some context in terms of how the actual socket call is made, I see that the emmiter is from the karma.js file, but how is this actually emmited for reporter to pick up. By the looks of it is through socket.io, like just wanted to figure out if the following from https://github.com/karma-runner/karma/blob/master/client/karma.js is actually called or not:

```js
  this.info = function (info) {
    // TODO(vojta): introduce special API for this
    if (!startEmitted && util.isDefined(info.total)) {
      socket.emit('start', info)
      startEmitted = true
    } else {
      socket.emit('info', info)
    }
  }
```

**Comment by dignifiedquire** [comment]
It is called and should be working afaict. But I have never tried to use it so there might be issues with it.

**Comment by devanshah1** [comment]
@dignifiedquire If I was to use socket.io on client side and dispatch an custom event and then have the reporter listening on this event, would this work?

**Comment by devanshah1** [comment]
@dignifiedquire any idea on an ETA, in terms of if this is in fact an issues in Karma or something I am doing that is wrong to use the actual API?

**Comment by surya66** [comment]
I am also seeing the same issue with this API, is there a ETA on this?

**Comment by devanshah1** [comment]
@vojta

**Comment by devanshah1** [comment]
@dignifiedquire @wesleycho I used the `localStorage.debug = '*';` option in the browser to enable the logs in karma to see if the info emit was going through, I did see that the emit was dispatch. Do you happen to know where I can look to verify if the reporter has received it or to verify if the emmiter is registered from the reporter.

**Comment by devanshah2** [comment]
@dignifiedquire @wesleycho @maksimr Not sure if you have had a change to take a look at this one.

**Comment by maksimr** [comment]
After some investigation, I think it never worked as you want.
Browser emits [only 'browser_log'](https://github.com/karma-runner/karma/blob/master/lib/browser.js#L107-L113) event.
Yes, [all log information implemented through 'info' event](https://github.com/karma-runner/karma/blob/master/client/karma.js#L96).

**Answers to questions**:

> Are you aware of any karma reporter plugins which are using the window.karma.info API?

Yes, karma itself because karma sends [`console.log`](https://github.com/karma-runner/karma/blob/master/client/karma.js#L96) through **info** method.

> Do you know of any other way to send arbitrary objects to the server from the client?

As a workaround(hack), you can inject [**executor**](https://github.com/karma-runner/karma/blob/master/lib/server.js#L70) to you reporter and [use sockets directly](https://github.com/karma-runner/karma/blob/master/lib/server.js#L41).


> how it should be used? 

As in your example, only the event will be named as 'browser_info'.

**client**:
```js
 window.__karma__.info({foo: 'foo'});
```

> @dignifiedquire If I was to use socket.io on client side and dispatch an custom event and then have the reporter listening on this event, would this work?

No, because emitter it's not socket, only [browser subscribed on all sockets events](https://github.com/karma-runner/karma/blob/master/lib/browser.js#L72) so you could create custom method in custom browser launcher like 'onFoo' and send event 'foo'.
**server**:
```js
emitter.on('browser_info', () => {});
```

> API would it be able to be picked up by any reporter that is registered

No matter reporter, browser or another code. If you inject **emitter** and subscribe on 'browser_info' you will receive event.


> And Also would the API only work if where you are calling it from is part of a karma start function.

I think it will be called only if browser starts to execute tests as It was done for ['browser_log'](https://github.com/karma-runner/karma/blob/master/lib/browser.js#L102-L104)

>  By the looks of it is through socket.io, like just wanted to figure out if the following from https://github.com/karma-runner/karma/blob/master/client/karma.js is actually called or not:

Yes, it works

>any idea on an ETA, in terms of if this is in fact an issues in Karma or something I am doing that is wrong to use the actual API?

I will try add such functionality soon

cc @devanshah1 @devanshah2

**Comment by devanshah1** [comment]
@maksimr Thanks a lot for taking a look at this. So the PR that you added I should be able to add 

```js
emitter.on('browser_info', () => {});
```

to the reporter and then on the client side stilling having:

```js
window.__karma__.info({foo: 'foo'});
```

will make things work right?

**Comment by maksimr** [comment]
@devanshah1 yup

**Comment by devanshah1** [comment]
@maksimr Awesome thanks a lot for this PR

**Comment by devanshah1** [comment]
@dignifiedquire @maksimr Any idea on when this can be released?

**Comment by dignifiedquire** [comment]
I will try to make a release over the weekend

**Comment by devanshah1** [comment]
@dignifiedquire Thanks a lot

**Comment by devanshah1** [comment]
@dignifiedquire @maksimr Thanks a lot for this, works like a charm.
