### ISSUE TITLE
Script error. thrown for no reason

### ISSUE THREAD

**Issue by Pasupathi-Rajamanickam** [karma-runner/karma#2755]
### Expected behaviour
Should run test as before
### Actual behaviour
Same tests that were running on 26th not running for me, throwing some errors which doesn't have any good explanations
### Environment Details
Windows 10, 8, Linux Ubuntu
Tried chrome and phantom js.
- Karma version (output of `karma --version`): "raw": "karma@^0.13.21" 

When I change some of the `it` name to something else, the other one starting to throw this error. And if I commit everything still getting this error.

**Comment by maksimr** [comment]
@popkutty look at the issue https://github.com/karma-runner/karma/issues/543 and https://github.com/karma-runner/karma/issues/1268#issuecomment-70422477

**Comment by ramuda** [comment]
probably you need ts-helpers

**Comment by devoto13** [comment]
Thanks for the bug report! Unfortunately without a reproduction there is nothing we can do about it. If you still experience this problem, please open a new issue and make sure to provide a way for us to reproduce it. Then we can identify the root cause and either fix it or point out at the configuration error.
