### ISSUE TITLE
`Object.values` stopped working from Karma 1.7.0 -> 2.0.0

### ISSUE THREAD

**Issue by juanca** [karma-runner/karma#2922]
### Expected behaviour

Karma configuration should work from 1.7 with 2.x

### Actual behaviour

Karma configuration file breaks when starting karma.

```
12 01 2018 23:34:36.932:ERROR [config]: Error in config file!
 TypeError: Object.values is not a function
```

### Environment Details

- Karma version (output of `karma --version`): 2.0.0
- Node version: 6.11.5

### Steps to reproduce the behaviour

1. Add `Object.values({ foo: 1 })` in karma configuration file.
2. Run karma

I used to work. I'm not even sure how it used to work since `Object.values` is not fully support in node 6 without a configuration flag (`--harmony`).

Did Karma polyfill that particular method? Was that removed in the latest release?

**Comment by naganowl** [comment]
https://github.com/karma-runner/karma/commit/60dfc5ce1b9d7aab0047123291cdd52195a69a9a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by juanca** [comment]
That makes sense.

I think the migration logs should point this out?

If the idea is that it's the problem of the user then feel free to close this issue.

**Comment by johnjbarton** [comment]
@naganowl Thanks for the explanation.  This issue should help others realize they should no longer use the now obsolete polyfill.

**Comment by naganowl** [comment]
Actually to confirm this even further, the more precise commit is https://github.com/karma-runner/karma/compare/v1.7.0...v2.0.0#diff-e8e0621a959fd2639bcc23cd2601f67fL10

The commit mentioned in my previous comment removes `babel` from karma's internal toolchain (i.e. using it for running specs testing karma's functionality). The line referenced addresses https://github.com/karma-runner/karma/pull/2690 which in previous versions ended up pulling in `core-js` that by default pulls in ES6 and ES7 features where [`Object.values`](https://github.com/zloirock/core-js/blob/v2.5.3/modules/es7.object.values.js) is one of them.

This issue is informative for others, though updating the changelog with the PR/commit would be helpful as well.
