### ISSUE TITLE
Browser crashed in Angular2 Component Test

### ISSUE THREAD

**Issue by Tomek6789** [karma-runner/karma#2970]
### Expected behaviour
Browser should not crashed.
Test should failed without crashing the browser.
### Actual behaviour
07 04 2018 11:30:02.320:ERROR [launcher]: PhantomJS (or Chrome)  crashed.
### Environment Details
Please check package.json
https://github.com/Tomek6789/KarmaAngular2/blob/master/package.json
node: 6.9.4
npm: 3.10.10
Ubuntu 16.04.4 LTS

- Karma version (output of `karma --version`): 2.0.0
- Relevant part of your `karma.config.js` file
https://github.com/Tomek6789/KarmaAngular2/blob/master/karma.conf.js

### Steps to reproduce the behaviour
1. Download repo https://github.com/Tomek6789/KarmaAngular2
2. Npm install
3. Ng test

Please check https://github.com/Tomek6789/KarmaAngular2/blob/master/src/app/app.component.spec.ts file.

### More info:
This project was generated with Angular CLI version 1.2.0.

This is standard angular component test.
If in this line is *ngIf="**!**isVisible" than test passed. But if some dev change to *ngIf="isVisible" 
Than browser crashed.
I tested this on Chrome and PhantomJS.

https://github.com/Tomek6789/KarmaAngular2/blob/master/src/app/app.component.spec.ts#L12

Can anyone help me understand what's going on here? 
Why browser crashed ?

**Comment by johnjbarton** [comment]
I assume that "browser crashed" means that the chrome executable binary exited without a command from the process that launched it. If this is true, then the problem is a chrome browser bug.  Ensure you are using the latest chrome browser.  You can try to report a bug to crbug.com but you will first need to create a tiny reproduction, say a single short html file.

But it could also be that the launcher is ending the browser process.  You can try to set `--log-level debug` to verify the actions.  In this case the appropriate place to ask is the karma-chrome-launcher project.

Angular testing seems to have a large number of issues and a large number of users. So another direction to look for information is with angular discussion groups or on stackoverflow.

Finally if all else fails try an alternative implementation that may not trip on whatever underlying problem occurs here. In any case this is not a issue that the karma-runner team can fix.

**Comment by Tomek6789** [comment]
Thanks for responde ! 
Sorry for creating issue in wrong repository.

I found solution to fix this bug.
It's jasmine-core. I only need to upgrade to 3.1.0 version.
