### ISSUE TITLE
version 1.7.1 appears twice in CHANGELOG.md

### ISSUE THREAD

**Issue by apetro** [karma-runner/karma#3119]
### Expected behaviour

Version `1.7.1` would appear at most once in `CHANGELOG.md`, with a clear articulation of what's in that release.

### Actual behaviour

`CHANGELOG.md` includes two entries for version `1.7.1`, with different release dates and release change documentation.

### Environment Details

(Not relevant.)

### Steps to reproduce the behaviour

1. Desire to understand the `1.7.1` release, e.g. when trying to understand https://github.com/karma-runner/karma/commit/ec92ea9 's inclusion in a `1.7.1` tag when trying to understand https://github.com/karma-runner/karma/issues/2912#issuecomment-415837780 .
2. Examine `CHANGELOG.md`
3. Become confused about which entry for `1.7.1` is controlling.

**Comment by johnjbarton** [comment]
The definitive history of the project is written in the commits to `master`. 

The 1.7.1 log was added twice because it was generated by an tool and a second 1.7.1 tag was added to the repro some how.   A PR to improve the project tooling would be welcome.

Fix-ups for the history can be followed up on #2912
