### ISSUE TITLE
How to use results object on run_complete

### ISSUE THREAD

**Issue by erpankajsingla** [karma-runner/karma#3145]
I am using the below code. 

```
server.on('run_complete', function (browsers, results){
        if (results.failed) {
            throw new Error('Karma: Tests Failed');
        }
        gutil.log('Karma Run Complete: No Failures');
        done();
    });
```

Where can I find more documentation/examples for results object? What other properties can I use from the results object?

I didn't find any detail on http://karma-runner.github.io/2.0/dev/public-api.html

**Comment by johnjbarton** [comment]
Just add a line
```js
console.log('results', results);
```
to see the object.

Their is no complete definition of the results object because it is sent by the 'framework adapter', eg karma-jasmine, to the 'reporter', eg karma-jasmine-reporter.  The karma-runner only relies on a few properties.  In general the framework adapter can add more info and the reporter can format it.

**Comment by erpankajsingla** [comment]
I tried console.log, it just gave `[object Object]`. But I got a suggestion from stackoverflow which worked. 

`JSON.stringify(results)`

which printed 

`{"success":89,"failed":0,"error":false,"disconnected":false,"exitCode":0}`
