### ISSUE TITLE
Problem using Karma with Docker

### ISSUE THREAD

**Issue by EricZLou** [karma-runner/karma#3318]
### Expected behaviour
After running the Docker command, Karma server opens on localhost:9876 without needing to manually open Chrome and go to localhost:9876. 
At the end of the test script, Chrome closes safely without being forcefully closed. 

### Actual behaviour
Need to open Chrome and go to localhost:9876 for the test script to start running.
After all of the tests successfully run, Chrome seems to not close correctly.
```
Chrome have not captured in 60000 ms, killing.
Chrome was not killed in 2000 ms, sending SIGKILL.
Chrome was not killed by SIGKILL in 2000 ms, continuing. 
```

### Environment Details
- Relevant part of your `karma.config.js` file
![image](https://user-images.githubusercontent.com/21316782/58661469-ddf8d900-82dc-11e9-8c2f-1526436af870.png)

**Comment by johnjbarton** [comment]
I guess that you don't have chrome in the container.  

Look through the debug log to see if chrome launched.

**Comment by ezl-13** [comment]
Hey @johnjbarton thanks for your response!
Do you know how I can install chrome in the container?

![image](https://user-images.githubusercontent.com/21316782/58986651-be592900-8792-11e9-967b-a4a405dc57b6.png)

This screenshot shows "connected on socket". This prints when I manually go to localhost:9876. Does this mean that Chrome is installed since it connects?

**Comment by johnjbarton** [comment]
On the one hand you have posted a screenshot showing chrome being launched as part of the karma run. It connects and configures.

On the other hand you mention multiple times manually going to localhost:9876.  I don't understand what this has to do with the  browser launch in the screenshot or what your issue is here.

**Comment by ezl-13** [comment]
Sorry, let me re explain:
1. Chrome is launched when the docker command that runs the test script is run
2. If I do not manually go to localhost:9876, the output stops after it configures. After a while, it will kill itself with 
```
Chrome have not captured in 60000 ms, killing.
Chrome was not killed in 2000 ms, sending SIGKILL.
Chrome was not killed by SIGKILL in 2000 ms, continuing. 
```
3. If I manually go to localhost:9876, then the output continues with "serving..." All of the tests are successfully run because it says "1241 of 1241 tests SUCCESS"
But the same error as above prints:
![image](https://user-images.githubusercontent.com/21316782/58996526-78f62500-87ad-11e9-9802-38bb0ad05edb.png)

What I'm unsure about is why I must manually type in "localhost:9876" into my Chrome browser in order for karma to connect to the socket. 
I'm also unsure why the error (Chrome have not captured, Chrome was not killed...) prints even when all of the tests ran. Is this even an error? 

Thank you so much for your help.

**Comment by johnjbarton** [comment]
Ok that helps a lot!

karma-runner opens a server and runs tests in any browser that connects. It also launches browsers you specify in the config. So in your case karma launches chrome but that browser fails. Then you connect by opening the localhost:9876 and karma runs the test in your browser.

But I'm still unclear on the case where you just let the command until failure, *not* opening any links in another browser.  Can you post the log for that case?

**Comment by ezl-13** [comment]
Ahhh thanks for that response. That makes sense. Do you know of any reasons why the browser that karma launches might be failing? 
And of course -- here are both of the possible outputs.

**Output 1: I run the Docker command, go to my own Chrome browser and go to localhost:9876**
Screenshot is in my previous message.

**Output 2: I run the Docker command and don't do anything else**
You can see the times of the output logs to see where it waits for the 60000(?) ms. 
![image](https://user-images.githubusercontent.com/21316782/59083160-17b47b80-88ab-11e9-8648-1564b0378694.png)

Thank you!

**Comment by johnjbarton** [comment]
According to your "don't do anything else" log, karma launched chrome and waited for it to open the port 9876.  In 120s Chrome did not open the port. So karma tried to kill the process by signalling it. That also failed. So eventually karma killed its launcher subprocess.

I suppose that Chrome could have never started (eg wrong exe), started but crashed, started but its network is partitioned from karmas, and so on. So you need to come up with some ways of isolating the issue.   Try copying the command line and running it in the docker image.  Look for flags on Chrome that cause verbose logging. Swap out the chrome command for "echo" or some other command known to work and to give IO.

One thing I discovered with Chrome is that it has to have write privileges to some special directory or it can fail mysteriously.

**Comment by ezl-13** [comment]
I see. Starting with that first point about "Chrome could have never started," is having this enough? Are there other places where I should check to make sure Chrome is included?
![image](https://user-images.githubusercontent.com/21316782/59578359-d46dc000-9095-11e9-97f3-7dc022b00b32.png)

**Comment by johnjbarton** [comment]
Well I meant you need to figure out if the chrome executable started in your actual run.  I don't use docker so I'm just trying to give suggestions.

**Comment by ezl-13** [comment]
Ah got it. I'll keep working on this. Thanks a lot for your tips @johnjbarton

**Comment by devoto13** [comment]
From the previous comments looks like there is nothing to fix on the Karma side. Please open a new issue with a minimal reproduction of the problem if you still believe that Karma is doing something wrong here.

PS You'll need to make sure that Chrome has started successfully (check that there is a running process with `ps` or something) and that Karma page didn't crash and was able to connect back to the Karma server. If you run Karma using headless Chrome you can use [`--remote-debugging-port`](https://developers.google.com/web/updates/2017/04/headless-chrome#frontend) to connect Chrome Debugger and check for browser/network errors.
