### ISSUE TITLE
angular js project urlRoot does not redirect path for the context.html

### ISSUE THREAD

**Issue by MichaelOdumosu57** [karma-runner/karma#3357]
### Expected behaviour
context.html  makes XHR TO /karma when urlRoot  = '/karma'
### Actual behaviour
context.html makex XHR to /  when urlRoot  = '/karma'
### Environment Details
ubuntu 16.04.5 LTS
proxy: nginx   1.16.1
node: 10.16.3
npm: 6.9.0

  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "chromedriver": "^76.0.1",
    "core-js": "^2.5.4",
    "cors": "^2.8.5",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.7",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }

- Karma version (output of `karma --version`):

  "karma": "~4.0.0",
- Relevant part of your `karma.config.js` file

    basePath: '/karma',  
    browsers: ['ChromeHeadless'],
    customContextFile:'customContextFile.html',
    urlRoot: '/karma'

### Steps to reproduce the behaviour

1. generate a new angular app and modify karma.conf.js with my mods
2. take a http web server or proxy provide for a /karma location and have a proxy _redirect to 
http://localhost:9876/karma, (disable caching if you like)
3.go to http://localhost:9876/karma (trust me it will redirect to client.html), and check out the console.log in devTools, if you follow to the source of the XHR you will see context.html
4. the <base href = '/'> means urlRoot did not get to that part of the app idk if its a jasmine thing

also i tried to provide for a  customContextFile option but karma seemed to over look it as i disabled caching everywhere I could, altough its a good solution I rather urlRoot knockout that tiny enormous bug

**Comment by MichaelOdumosu57** [comment]
Anyone get a chance to take a look yet

**Comment by devoto13** [comment]
When I run `ng test` from the new Angular CLI project, then Karma loads its files from the `/` (default value for `urlRoot`). E.g.

- `http://localhost:9876/socket.io/socket.io.js`
- `http://localhost:9876/karma.js`
- `http://localhost:9876/context.html`
- `http://localhost:9876/context.js`

When I add `urlRoot: '/karma/'` to the config file and run `ng test` again, then Karma loads most of its files from the `/karma/` path. E.g.

- `http://localhost:9876/karma/socket.io/socket.io.js`
- `http://localhost:9876/karma/karma.js`
- `http://localhost:9876/karma/context.html`
- `http://localhost:9876/context.js` <- **broken** (file is correctly served on http://localhost:9876/karma/context.js, but `context.html` tries to load it from the wrong URL)

Note that everything works correctly with Karma's built-in context file.

Angular CLI uses [custom context file](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma-context.html), which leads to this bug. It adds `<base href="/">`, which forces `context.html` to request `http://localhost:9876/context.js` instead of `http://localhost:9876/karma/context.js`.

Closing as this is a bug in Angular CLI and not in Karma. Please re-open this issue in https://github.com/angular/angular-cli and link to this comment for investigation results.
