### ISSUE TITLE
Problem testing code that relies on window.location value

### ISSUE THREAD

**Issue by mjgs** [karma-runner/karma#3368]
### Expected behaviour

Expected that it would be possible to change window.location in test setup.

### Actual behaviour

Actual behaviour is that window.location is always set to 'context.html'.

### Environment Details

Karma version: 4.3.0

### Steps to reproduce the behaviour

1. Modify window.location before tests start (I use a file at start of karma file array in karma config)
2. Run tests
3. See that window.location is set to context.html in tests

How do you change the value of window.location in test setup?

**Comment by johnjbarton** [comment]
> How do you change the value of window.location in test setup?

You can't. Karma is designed for unit tests.  Search "webdriver" or "cypress" for e2e testing.

**Comment by mjgs** [comment]
Thanks for the details. 

Could you provide a bit more details about this limitation, is this specific to window.location or is it not possible to change any property on the window object?

**Comment by johnjbarton** [comment]
The karma-runner works by hosting the test code in the same browsing context (`window`) it is running in. So any operation on `window` that compromises the runner will fail. The operation list is short, including `window.location` (because then karma is erased) and `window.__karma__` (because that is karma storage) and `window.console` (log forwarding).  The list itself is not specified since unit testing is the design focus, but most other properties can be mutated.
