### ISSUE TITLE
 Executed 0 of 0 SUCCESS

### ISSUE THREAD

**Issue by meenanarendra** [karma-runner/karma#3403]
### Expected behaviour
It should run the test cases
### Actual behaviour
 Executed 0 of 0 SUCCESS
### Environment Details
use this repo for sample code.
https://github.com/meenanarendra/MyKarmaApp/tree/master
- Karma version (output of `karma --version`):

- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1. Karma start
2.
3.

**Comment by johnjbarton** [comment]
Try running with `--logLevel=DEBUG`. Try running with `--noSingleRun` then opening the debugger on the web page. My first guess is that you have a syntax error in your test code so the tests never get registered with the runner, leading to 0 tests.

**Comment by devoto13** [comment]
I'm not very familiar with the RequireJS, but looks like a misconfiguration to me. Below diff makes tests pass:

```diff
diff --git a/karma.conf.js b/karma.conf.js
index dd2f3c2..8224f4a 100644
--- a/karma.conf.js
+++ b/karma.conf.js
@@ -17,9 +17,6 @@ module.exports = function(config) {
     files: [
       {pattern: 'src/*.js', included: false,nocache:false},
       {pattern: 'test/*.js', included: false,nocache:false},
-      {pattern: 'node_modules/mocha/mocha.js', included:false, watching: false,nocache:true},
-      {pattern: 'node_modules/chai/chai.js', included:false, watching: false,nocache:true},
-      {pattern: 'node_modules/sinon/lib/sinon.js', included:false, watching: false,nocache:true},
       {pattern: 'node_modules/jquery/dist/jquery.js', included:false, watching: false,nocache:true},
       'test-main.js'
     ],
diff --git a/test-main.js b/test-main.js
index 20ced97..8ae886f 100644
--- a/test-main.js
+++ b/test-main.js
@@ -1,5 +1,5 @@
 var allTestFiles = []
-var TEST_REGEXP = /(spec|test)\.js$/i
+var TEST_REGEXP = /(spec|Tests)\.js$/i

 // Get a list of all the test files to include
 Object.keys(window.__karma__.files).forEach(function (file) {
@@ -14,13 +14,12 @@ Object.keys(window.__karma__.files).forEach(function (file) {

 require.config({
   // Karma serves files under /base, which is the basePath from your config file
-  baseUrl: 'base',
+  baseUrl: '/base',
   paths: {
     'mocha': 'node_modules/mocha/mocha',
     'chai': 'node_modules/chai/chai',
     'sinon': 'node_modules/sinon/lib/sinon',
     'jquery': 'node_modules/jquery/dist/jquery',
-    'myCodeTests': 'test/myCodeTests',
     'myCode': 'src/myCode'
      },
     shim:{},
diff --git a/test/myCodeTests.js b/test/myCodeTests.js
index c802fae..3cfe861 100644
--- a/test/myCodeTests.js
+++ b/test/myCodeTests.js
@@ -1,4 +1,4 @@
-define('myCodeTests',['require','jquery','src/myCode'],function (require,$,myCode) {
+define('test/myCodeTests', ['require','jquery','myCode'],function (require,$,myCode) {

 describe('Top test', function () {
     describe('#endsWith()', function () {
```

1. You exclude files which were included by the `mocha`, `chai` and `sinon` frameworks, which causes tests to crash as these files are missing from the page.
2. Wrong regular expression to generate `deps` array, which does not match your test file.
3. Wrong module name (`myCodeTests` -> `tests/myCodeTests`), the later is what you add to the `deps` array and what will be executed. RequireJS just waits indefinitely since requested module is never defined.
4. `baseUrl` was set incorrectly, which caused warnings from Karma as URLs were not matched and Karma caching was not applied properly.

Closing as per above.
