### ISSUE TITLE
Date object does not match when Date gets called to component

### ISSUE THREAD

**Issue by argelj289** [karma-runner/karma#3579]
I'm getting a bug when I pass the Date object into the component's variable

its like getting converted into very late month

example:

from spec file:

```
let dateToday = new Date();

component.modelDate = {
  year: dateToday.getFullYear(), //<-- 2020
  month: dateToday.getMonth(), //<-- 11
  day: dateToday.getDate() //<-- 27
};

```

when I execute `ng test --code-coverage=true` and the component gets the mocked value:

```
this.myModelDate = {
  year: this.modelDate.year, //<-- 2020
  month: this.modelDate.month, //<-- 10
  day: this.modelDate.day //<-- 27
};

```

Angular version: 10.1.3
Karma: 5.0.0

**Comment by devoto13** [comment]
Thanks for the issue, but this is does not look like a Karma bug report or a feature request. Please use [StackOverflow](https://stackoverflow.com) for support requests or open a new issue providing a minimal reproduction using only Karma if you still believe that this is problem is caused by Karma test runner.
