### ISSUE TITLE
v6 includes socket.io v3 which interferes with the type of `setTimeout`

### ISSUE THREAD

**Issue by falsandtru** [karma-runner/karma#3623]
Because that type is overloaded by @types/node type package imported by karma: https://github.com/microsoft/TypeScript/issues/32273

**Comment by devoto13** [comment]
This issue usually happens when both `lib.dom.d.ts` and `@types/node` are present in the same TS compilation. However it's not Karma, but one of its dependencies, which depends on `@types/node` package (namely socket.io@3), so it's not something we can fix here and it is better to report this issue to that socket.io repo.

```
npm list @types/node
karma@6.0.0 /Users/devoto13/Projects/karma
...
└─┬ socket.io@3.0.4
  └── @types/node@14.14.13
```

As a workaround, you can explicitly specify global types you want to be included in the compilation using [types](https://www.typescriptlang.org/tsconfig#types) property in `tsconfig.json`. The presence of the `types` property (even empty array) will prevent automatic inclusion of all installed `@types/*` packages in the compilation and should therefore mitigate the problem.

**Comment by johnjbarton** [comment]
how

**Comment by devoto13** [comment]
I guess the resolution here is: use a workaround and specify `types` in your `tsconfig.json`. 

There is really nothing we can do about it on the Karma side. And `socket.io` package contains types for server-side code (which do need a `@types/node` dependency), so `@types/node` can not be removed from their dependencies either.
