### ISSUE TITLE
ng test command crashed due to Karma webpack couldn't resolve the CoreModule.

### ISSUE THREAD

**Issue by Waseem-Isaac** [karma-runner/karma#3770]
**Vesrions used:** 

"@angular/core": "^12.2.15",
"@angular-devkit/build-angular": "~12.2.15",

"karma": "~6.3.4",
"karma-chrome-launcher": "~3.1.0",
"karma-cli": "~2.0.0",
"karma-coverage-istanbul-reporter": "~3.0.2",
"karma-jasmine": "~4.0.0",
"karma-jasmine-html-reporter": "^1.6.0",
"karma-junit-reporter": "^1.2.0",

**The following error message appears only after running ng test :**

```
 An error was thrown in afterAll
  Uncaught TypeError: Cannot read properties of undefined (reading 'CoreModule')
  TypeError: Cannot read properties of undefined (reading 'CoreModule')
      at Module.CoreModule (http://localhost:9876/_karma_webpack_/main.js:4105:108)
      at Module.3467 (http://localhost:9876/_karma_webpack_/webpack:/src/app/home/home.module.ts:17:5)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Module.36747 (http://localhost:9876/_karma_webpack_/main.js:271:75)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Module.82182 (http://localhost:9876/_karma_webpack_/main.js:15425:73)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Module.44466 (http://localhost:9876/_karma_webpack_/main.js:17638:83)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Module.40294 (http://localhost:9876/_karma_webpack_/main.js:3226:83)
```

**I have the following files structure :**
```
 ->src/app/core/
              -> index.ts
              -> core.module.ts
              -> ..
->src/app/folder/
              -> module.ts
```

I'm trying to import `CoreModule` from `src/app/core/index` which includes `export * from './core.module';` inside `src/app/folder/module.ts` using `import { CoreModule } from '@app/core';`

However it seems `src/app/core/index.ts` file fails to export `CoreModule`.

**src/app/core/core.module.ts :**
```
@NgModule({
  imports: [CommonModule, HttpClientModule, TranslateModule, RouterModule, SharedModule, TourMatMenuModule],
  providers: [
    {
      provide: HttpClient,
      useClass: HttpService,
    },
    {
      provide: RouteReuseStrategy,
      useClass: RouteReusableStrategy,
    },
    ApiService,
  ],
  declarations: [ComponentA, ComponentB],
})
export class CoreModule {
  constructor(@Optional() @SkipSelf() parentModule: CoreModule) {
    // Import guard
    if (parentModule) {
      throw new Error(`${parentModule} has already been loaded. Import Core module in the AppModule only.`);
    }
  }
}
```

**Comment by devoto13** [comment]
Most likely you have a cyclic reference in your code.

**Comment by Waseem-Isaac** [comment]
Thanks @devoto13 for your answer.
PS: this only occuers for the test environment compilation. nothing wrong with `ng serve` or `ng build --prod`.
Can I just disable this detection for now, to not block compiling the whole app ?

**Comment by devoto13** [comment]
That means that the circular reference probably only appears in the test code, but not in the production code. I don't think you can "disable" something to get it to work. You will need to use some sort of linter/tool to find the circular dependency and break it by either changing the import path or re-ordering exports in your `index.ts` files. And the cycle dependency is not necessarily the reason, it's just my educated guess based on the information you've provided. It's up to you to debug and confirm it. You can read more about circular dependencies, e.g. [here](https://spin.atomicobject.com/2018/06/25/circular-dependencies-javascript/).

You can surely keep using `index.ts` files if you wish to. I just recommended that because it is a common (but not the only) cause for the issue you're experiencing.

**Comment by Waseem-Isaac** [comment]
@devoto13 
As far as I know . the circular dependencies doesn't break the app compiling for both the production & the test code enviroments. will check & fix it btw.
But even when I tried to import the module directly (fom its path without index.ts) I got the following error: 
 `Uncaught ReferenceError: Cannot access 'CoreModule' before initialization`

**Comment by devoto13** [comment]
This exactly means that you have a circular dependency, CoreModule attempts to access X to initialize, but X, in turn, attempts to access CoreModule, which can not proceed and throws.

**Comment by Waseem-Isaac** [comment]
@devoto13 
Even if I removed the CoreModule import at this module .. I found the same error for the next module :D 
I wonder because same code structure is working in another project without `ng test` breaking.

**Comment by Waseem-Isaac** [comment]
I'm declaring a pipe in `CoreModule` , Which is importing some class from `app.module.ts` file. And this was the poblem.
But I still can't realise what makes the test code detect it and crash .but not the production code  :))

**Comment by michahell** [comment]
I just had exactly this cause for a related issue with Angular + Karma too. What I got were cryptic `afterAll` errors.
I **could** however track back the issue to a very specific Service import - which before a refactor just used to work because nothing changed there.
However, **I had introduced barrels for, among others, also this Service**.
As it turns out, the services barrel import came áfter the components / directives barrel import. 
**This is what trips the Karma Angular build up!**
This definitely makes me less interested in barrels. for now, I've kept them, but in the "master" barrel file I have added a gigantic disclaimer for those after me to make sure they check import orders.
