### ISSUE TITLE
Types (flow) error when use coverage

### ISSUE THREAD

**Issue by Merynek** [karma-runner/karma#3778]
When I add coverage in karma conf, its return lot of types error, but without coverage its not.
I use own webpack for build typescript etc...

I run:
```
"test": "node --max_old_space_size=8000 node_modules/karma/bin/karma start karma.conf.js",
```

package.json
```
    "karma": "^5.2.3",
    "karma-chrome-launcher": "^3.1.0",
    "karma-commonjs": "^1.0.0",
    "karma-coverage": "^2.2.0",
    "karma-jasmine": "^3.1.1",
    "karma-typescript": "^5.0.2",
    "karma-webpack": "^4.0.2",
```

karma.conf.js
```
const webpackConfig = require('./webpack.config.js');
webpackConfig.entry = {};

module.exports = function (config) {
    config.set({
        frameworks: ["jasmine"],
        files: [
            "./test/boot.spec.ts",
            "./src/app/**/*.ts",
            "./test/**/*.ts"
        ],
        reporters: ['coverage'],
        preprocessors: {
            // add webpack as preprocessor
            'test/**/*.ts': ['webpack'],
            'src/app/**/*.ts': ['coverage'] //for coverage
        },
        webpack: webpackConfig,
        browsers: ["Chrome"],
        logLevel: config.LOG_ERROR
    });
};
```
Errors:
![image](https://user-images.githubusercontent.com/6883795/159500864-43d97f6a-7109-4714-9743-47324305f104.png)

**Comment by jginsburgn** [comment]
My first suggestion would be to update all your Karma deps. Try that.

**Comment by devoto13** [comment]
Well, you attempt to instrument unprocessed **TypeScript** files using `karma-coverage` plugin. It will not work as the plugin can only instrument JavaScript files. Given that you also use `karma-webpack` plugin, the coverage instrumentation should be done by Webpack, because `karma-webpack` takes over budling and serving from Karma completely.

I think the best thing for you is to find a guide on the internet on how to set up the code coverage with TypeScript and Webpack and follow it. E.g. [this guide](https://github.com/mcliment/typescript-karma-webpack-coverage-sample). It shows how to [instrument code using Webpack](https://github.com/mcliment/typescript-karma-webpack-coverage-sample/blob/db23e83c9f34fcc4a035703bbeaea656cdbaea80/webpack.config.js#L19) and how to configure coverage reporting using [karma-coverage-istanbul-reporter](https://github.com/mcliment/typescript-karma-webpack-coverage-sample/blob/db23e83c9f34fcc4a035703bbeaea656cdbaea80/karma.conf.js#L13) (you can use `karma-coverage` plugin as a reporter in its place which should work exactly the same).

**Comment by Merynek** [comment]
> Well, you attempt to instrument unprocessed **TypeScript** files using `karma-coverage` plugin. It will not work as the plugin can only instrument JavaScript files. Given that you also use `karma-webpack` plugin, the coverage instrumentation should be done by Webpack, because `karma-webpack` takes over budling and serving from Karma completely.
> 
> I think the best thing for you is to find a guide on the internet on how to set up the code coverage with TypeScript and Webpack and follow it. E.g. [this guide](https://github.com/mcliment/typescript-karma-webpack-coverage-sample). It shows how to [instrument code using Webpack](https://github.com/mcliment/typescript-karma-webpack-coverage-sample/blob/db23e83c9f34fcc4a035703bbeaea656cdbaea80/webpack.config.js#L19) and how to configure coverage reporting using [karma-coverage-istanbul-reporter](https://github.com/mcliment/typescript-karma-webpack-coverage-sample/blob/db23e83c9f34fcc4a035703bbeaea656cdbaea80/karma.conf.js#L13) (you can use `karma-coverage` plugin as a reporter in its place which should work exactly the same).

I tried it, but I got 2 issues.
1.  No coverage
![image](https://user-images.githubusercontent.com/6883795/160134218-f8663935-cf7c-48a1-96c3-a7f94bb954e5.png)
2. Infinite compile loop - after compile and run tests its (probably) detect changes and run recompile

Any idea?

**Comment by Merynek** [comment]
> Hard to say, but looks like your code was not instrumented to collect coverage. Have you added the corresponding Webpack loader?

This is my config:
![image](https://user-images.githubusercontent.com/6883795/160333763-be158d58-22cd-4151-bc85-6bdae4bc479d.png)

Any idea?

**Comment by devoto13** [comment]
Have you added `istanbul-instrumenter-loader` to your Webpack config? As shown [here](https://github.com/mcliment/typescript-karma-webpack-coverage-sample/blob/db23e83c9f34fcc4a035703bbeaea656cdbaea80/webpack.config.js#L19).

**Comment by devoto13** [comment]
Hope you were able to resolve your problem by now.
Closing as a stale support request.
