### ISSUE TITLE
[karma-server]: Server start failed on port 9876: Error: The target entry-point "ngx-siema" has missing dependencies:  - rxjs/BehaviorSubject  - rxjs/ReplaySubject  - rxjs/add/operator/publish  - rxjs/Observable

### ISSUE THREAD

**Issue by gouthmpllc** [karma-runner/karma#3790]
Please read https://karma-runner.github.io/4.0/intro/troubleshooting.html first.

After commenting "**/*.spec.ts",in  (Exclude Array ) tsconfig.json file , Getting above error.
if not commenting then below error.

An error was thrown in afterAll
  Uncaught Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
  Error: C:\Users file.component.spec.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property

**Comment by devoto13** [comment]
Most likely you have some misconfiguration in you Angular project. karma does not support Angular natively, but through an Angular plugin, so I would suggest to use [Angular's support channels](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question) where you have a much better chance to get help. I would also suggest to provide a minimal runnable project as it will allow people to troubleshot it and propose a good fix instead of just guessing.
