### ISSUE TITLE
Run each set of tests in separate iframe

### ISSUE THREAD

**Issue by hakubo** [karma-runner/karma#412]
This would make karma also superb for integration (and such) tests.
As they can easily pollute global variables or fixtures.

This would be awesome to have files variable in config file to accept something like:

``` JS
files = [
    ['file.js', 'file.spec.js'],
    ['lib.js', 'lib.spec.js']
]
```

or an object

``` JS
files = {
    'fileTest': ['file.js', 'file.spec.js'],
    'libTest': ['lib.js', 'lib.spec.js']
}
```

so you could name each set

and each array would be set of files to be loaded in a separate iframe
so you would not have to worry about polluting environment
and just focus on integration tests itself

**Comment by fredericoschardong** [comment]
@hakubo did you end up coding this feature? I need this for a plugging I am working on, it would be good to not start from scratch. Thanks!

**Comment by hakubo** [comment]
@fredericoschardong Unfortunately no. I have changed my stack in the meantime.

**Comment by bonitao** [comment]
+1, the proposed grouping syntax looks very nice.

**Comment by timdp** [comment]
While it's not an ideal solution, I've written a Karma plugin that injects an iframe with a postMessage bridge into Mocha tests. It's called [karma-mocha-iframes](https://github.com/timdp/karma-mocha-iframes) and there's also a [demo](https://github.com/timdp/karma-mocha-iframes-demo).

**Comment by sabberworm** [comment]
I’ve tried to generify @timdp’s solution. The result is [karma-iframes](https://www.npmjs.com/package/karma-iframes). It’s the same idea but should work with any adapter, not just mocha.

**Comment by timdp** [comment]
@sabberworm Are you sure it's the same idea? From the readme, it sounds like you're running each test _file_ in a separate iframe. My version runs each individual (Mocha) test in its own iframe to prevent each test from tainting the context for subsequent ones.

**Comment by bashmish** [comment]
This might be really helpful when testing custom elements (web components). For now there is only one single registry and no way to unregister an element. Though there is [this idea to have scoped registries](https://github.com/w3c/webcomponents/issues/716) which does not have a concrete proposal yet.

This [old discussion about the possibility to unregister](https://github.com/w3c/webcomponents/issues/152) didn't go further than pointing out that there are test frameworks which already run tests in iframes, which is the [web-component-tester](https://www.npmjs.com/package/web-component-tester). But web-component-tester is also very limited and only allows running individual suites in iframes, not individual tests. I created [a repo to show this behavior](https://github.com/bashmish/wct-ce-name-conflict). Looks like the above mentioned [karma-iframes](https://www.npmjs.com/package/karma-iframes) is similar to the WCT behavior.

I can understand that this use case is not trivial. But maybe it is time to reconsider and reopen the issue at least to explore this use-cases further.

**Comment by lancedikson** [comment]
I'm currently having the same situation with custom elements (Web Components) testing and struggling with setting up integration and unit tests, where each component can be registered only once and there's no way to unregister it. It produces very specific workarounds after all. Let's try to call active maintainers to re-check this issue and maybe re-open it because the problem is getting more and more common due to the growing popularity of WebComponents. @johnjbarton 🙏

**Comment by lancedikson** [comment]
One more hint for those, who suffer from the issue and don't want to use `karma-iframes` because of their drawbacks: I came up with a wrapping decorator for `@customElement()`:

```ts
import { customElement } from 'lit-element';

function customElementDecorator(tagName:string): any {
  const registeredElement = window.customElements.get(tagName);

  if (typeof registeredElement === 'undefined') {
    return customElement(tagName);
  }
  return () => {};
}

@customElementDecorator('my-component')
class MyComponent {
// ...
}
```
Then you can place this decorator to some optional requirement in webpack, for example, and use it only during testing, like this: 
```ts
const legitCustomElement = (NODE_ENV === 'testing') ? customElementDecorator : customElement;
export { legitCustomElement as customElement };
```

This workaround seems working for now, let's see how it goes when we have more tests. I hope there will not be any race conditions with registering elements from different parts of the code.
