### ISSUE TITLE
[Support] How do you load CDN scripts?

### ISSUE THREAD

**Issue by plus-** [karma-runner/karma#421]
Hello,

I'd like to unit test some functions which depends on jquery, YUI, and other libs available on CDN.
Is it possible to get them used by karma from their CDN url without having to download and maintain those files?

cheers,

**Comment by AndyBrownlie** [comment]
@vojtajina I have a similar issue with gapi. 
I am using google api platform, where I load the js on index.html. 

For karma, I have done as you suggested above and added the url (https://apis.google.com/js/platform.js) via files into the karma.conf.js.

However, when I execute my tests I get "ReferenceError: gapi is not defined". Is this because the script has not yet finished loading?

thanks in advance

**Comment by xveganxxxedgex** [comment]
@AndyBrownlie It may be a CORS issue - I just faced this myself with an identical situation. I declared the files in the karma config, but it wasn't actually loading the source due to CORS issues. 

Adding this to the karma config file fixed it for me:

`crossOriginAttribute: false,`

**Comment by AndyBrownlie** [comment]
hey @xveganxxxedgex  this worked!  great, thanks!

**Comment by luwes** [comment]
watch out with the above solution. it adds the script url once for each file.
I had an issue with https://unpkg.com/@webcomponents/custom-elements
calling the callbacks of the custom element multiple times...
