### ISSUE TITLE
Allow inserting source files in the HEAD / custom context.html

### ISSUE THREAD

**Issue by vojtajina** [karma-runner/karma#488]
Based on #430

**Let's allow custom `context.html` and `debug.html`.**

Add two config options:
- contextFile (default __dirname + '../static/context.html')
- debugContextFile (default __dirname + '../static/debug.html')

**Comment by aiboy** [comment]
Added support to add custom context.html / debug.html - in "Support for custom context and/or debug html files"  #1360 

Unlike other pull request this one is little bit cleaner and doesn't break existing unit tests

**Comment by UnsungHero97** [comment]
any update on when this change will be ready to use? I'd like to give this a try. I tried adding in the changes from the PR, but I'm running into problems; it seems like other places need to add in the extra parameter

**Comment by aiboy** [comment]
Sorry, my bad. To busy to finish the job. I will try to make appropriate pull request asap

**Comment by UnsungHero97** [comment]
@aiboy did you get a free moment to make that pull request?

**Comment by T-vK** [comment]
Another good point for custom context.html files is that ExtJs 6 for example wants `<html manifest="">` instead of just `<html>`. It's also a lot of work to change the config of Karma every time you add a new script to your index.html and you can't really use internal script in your index.html file because you couldn't tell Karma how to get it for the context.html. In my opinion Karma should definitely inject into a copy of the index.html.  
...and not being able to set the DOCTYPE may be another thing that could cause problems.  

I'm really looking forward to this being implemented.

**Comment by rosenfeld** [comment]
I believe there are many reasons why allowing custom HTML would be desirable. It gives other projects flexibility to do basically any kind of experimentation with Karma without having to fork the project.

In our specific case, we use oojspec to run unit and integration tests with a single runner. Most integration test runners out there are pretty slow, like Capybara, Selenium or anything using a real browser, headless like phantomjs or not.

OOJSpec doesn't enforce the way people should write code. If someone wants to be able to register events on DOM selectors which are never unregistered because it's not needed in the application, they shouldn't change the way they write their code just to satisfy their test runner limitations. So, one is free to register those events once in a `beforeAll` block and then run a set of tests, which may depend or not on previous tests (they are always run in the specified order by specification) which allows some integration scenarios to be tested more quickly than it would be if the tests had to be written in an independent way and also gives developers more flexibility on how they write code.

For this to work, OOJSpec has to run each set of tests, grouped in an specification file, in a separate iframe. OOJSpec currently uses sprockets to create such structure in a similar way adopted by other gems like Konacha and others. It would be awesome to be able to use Karma infra-structure to run a custom HTML runner created to be compatible with Karma API so that it reports the tests run correctly to the client console. It should be doable once we have the ability to specify how the HTML should be written. My plan is to integrate OOJSpec to webpack and test with Karma and stop using sprockets. Another advantage of running the tests in separate iframes is that you are able to test whether all required dependencies were correctly declared since only the dependencies for that test file are loaded in the isolated iframe.

**Comment by dignifiedquire** [comment]
Done in #1825
