### ISSUE TITLE
Excluding files from preprocessor

### ISSUE THREAD

**Issue by kimjoar** [karma-runner/karma#508]
In my current code base I keep all files (including tests) for a module/component in the same folder, e.g.

![menu](https://f.cloud.github.com/assets/5259/396728/9a18e940-a82d-11e2-8029-5d17da97e53f.png)

The problem is that I want test coverage for the module. Before I moved the specs into the module folder I used the following preprocessor:

``` javascript
preprocessors = {
    '**/resources/javascript/**/*.js': 'coverage'
};
```

Naturally that don't work anymore since it also includes all my tests (thereby increasing my code coverage metrics by quite a bit). As all the tests are named `*Spec.js` it should be quite simple to exclude them, but I can't seem to find a way given how the preprocessors are currently specified.

Excluding stuff when globbing appears to be quite difficult. Would it be possible to give the preprocessor an array of files instead? That would enable me to do the exclusion logic myself. Any thoughts on how this can be solved?

**Comment by tregusti** [comment]
@lazd It helped me in understanding how the patterns should be written. Thank you! I could've looked at the minimatch docs, but it's too early in the morning...

**Comment by scheffield** [comment]
@lazd Thank you! `{src,src/!to_exclude/**}/*.js` is exactly what I needed.

**Comment by thepian** [comment]
I always found it odd how some people instinctively separate implementation and tests into src and test directories, or other split out assets. They are usually closely related and you end up with parallel hierarchies. Then you need IDE support to relate them again on the assumption that test and source is called the same which is pushes you towards writing a test for each class / function which leads to box ticking rather than thinking about the problem at hand. Tools should get out of the way and let you structure a project in a way that works for the problem and project at hand.

**Comment by GitHubThomas** [comment]
I think the reason for this is that in statically types languages like java or c#, you have to seperate tests und source. Otherwise you would have to deploy the tests to production. Here it makes sense to build parallel hierarchies.
But in a dynamically typed language like javascript, it feels really good to have the tests in one place.

**Comment by Dipak1991** [comment]
Is there any way in which I can skip nested directory keep everything else in the coverage report ?

```
└── src/
    ├── index.js
    ├── index.js.text
    ├── index.test.js
    ├── README.txt
    ├── startuptest.js
    ├── lib/
    |   ├── util.js
    |   ├── util.test.js
    |   └── filters/
    |       ├── kalman.js
    |       └── lowpass.js
    ├── test/
    |   ├── main.js
    |   └── lib/
    |       ├── filters.js
    |       └── util.js
    └── vendor/
        ├── jquery.js
        └── three/
            ├── three.js
            └── three.fps.js
```

I want to exclude all files under my

`src/lib/!(filters)/**`

But want everything else under src in coverage report. 

OP - http://stackoverflow.com/questions/42105675/karma-config-to-exclude-nested-directories

**Comment by megamindbrian** [comment]
Using webpack, this is the only exclude expression that worked!
```
/(tests|node_modules|\.spec\.ts$)/
```
