### ISSUE TITLE
Script error. at 0:

### ISSUE THREAD

**Issue by adamwynne** [karma-runner/karma#543]
Whenever I use Karma on my CI server I get:

Chrome 26.0 (Linux) ERROR
    Script error.
    at :0

I've seen it before on my local dev (mac) box where it happens occasionally, but it happens every time on my CI (linux) box

Has anyone ever seen this, or does anyone have any ideas to try?

**Comment by kylethornton** [comment]
@lpsBetty just wondering what you did to fix this. I have the same exact scenario and just trying to figure out a way around it.

**Comment by adamwynne** [comment]
I just moved to PhantomJS and it went away

**Comment by lpsBetty** [comment]
@kylethornton if you debug your tests in the browser you can see the error in the console.. 

my error was caused by an external JS which was expecting a specific ID on a form element.. so I added the HTML in the test..

**Comment by kylethornton** [comment]
Thanks @lpsBetty. My error messages in the browser weren't as helpful, but I ended up just mocking $.getScript to give me more control of what happened with the callback. Since these are unit tests I only care about how my code is functioning anyway.

**Comment by lpsBetty** [comment]
ok, I am glad you found a solution!

**Comment by Deepakdubey90** [comment]
why phantomJs witrh karma throw error : ""Some of your tests did a full page reload!""  most of the time during UI Unit-Test-case . & how to fix it..?

**Comment by maxime1992** [comment]
I've had the exact same problem with angular cli.

Turns out it was a circular dependency (and I'm pretty glad that it was caught).

So if you've got that error when running `ng test`, just run instead `ng serve` which shows the circular dependencies as warnings, figure out which function, variable or whatever you've got to move and move it to break the circular dependency.

**Comment by ramuda** [comment]
probably you need ts-helpers

**Comment by trusktr** [comment]
I had this problem. In my case in karma-electron. It appears that when there are uncaught errors, the browser propagates the error to Karma somehow, but without all the details.

So what I did (and it is ugly) was I made karma wrap all my tests with `try-catch` blocks, and in the `catch(err)` block I call `console.log(err)` and then re-throw the error so that the error continues to propagate as usual.

This completely solved the issue for me, now any errors are logged to console.

One way that you can set this up is, at the top of your `karma.config.js` file,
  
- use a tool like `globby` to get a list of all your test files.
- for each test file
  - read the content
  - prepend the line `try {` at the beginning of the file (but after `import` statements if you're using those)
  - append a `} catch (e) { console.log(e); throw e }` line to the end of the file
  - Note, basically this try-catch wraps your `describe` calls.
  - Note, if you're using require, wrap the `require()` calls too (unlike with imports, which can't be wrapped) to catch more errors.
  - write the files to a new location, like `./tmp-karma-test-build`
- Now update your config file's `files` field to point to the new files, so Karma will load the modified test files instead of the original ones.
- In your script where you run the `karma` command, make sure to erase the `.tmp-karma-test-build` folder, and add it to your `.gitignore`

Basically that's what I did, more or less. Now when I run Karma, I see helpful error messages logged to console instead of just `Script error. at :0:0`.

Your mileage may vary if it isn't the same issue.

**Comment by trusktr** [comment]
If this is a problem in many browsers that Karma is running (not just karma-electron like in my case), then perhaps this is actually a bug in Karma and this issue may need to be re-opened.
