### ISSUE TITLE
Optional fail if coverage threshold not met

### ISSUE THREAD

**Issue by andrew-cunliffe** [karma-runner/karma#673]
I have recently started using Karma, and the team keeps adding code which drops the coverage below a level I am happy with, it would be great if Karma could fail the tests on CI based on a config setting like a percentage threshold e.g.
```js
coverageReporter = {
    threshold: 80
}
```

I might have a look at doing this too if I can however it might be relating to the plugin used for coverage?

Wanted to add this here as a possible new feature as I cant see any alternatives to when I get to putting my code in and finding others have not been adding tests for their code :)

**Comment by stramel** [comment]
This could probably be closed. Options that I have found:

 - Plugin: https://github.com/lithiumtech/karma-threshold-reporter
 - Manual Parsing / Istanbul Check Coverage call

**Comment by shivanykshenoy** [comment]
This issue is closed because it has been addressed in karma-coverage as per the following commit: https://github.com/karma-runner/karma-coverage/commit/bc63b1583ec95abbf4c74df5f8346e0c8f048220  

basically you add a check like below for the coverageReporter, in the karma.config file:

coverageReporter: {
  check: {
    global: {
       statements: 100,
       lines: 100,
       functions: 100,
       branches: 100
    }
 }
}

Thank you @Dignifiedquire!  Much appreciated ;-)

**Comment by reyraa** [comment]
`karma-threshold-reporter` fails only if the overall threshold of the test coverage is below defined value.
I think having the same possibility as per file basis would be helpful. for instance, we have important modules merged without a single line of unit test, just because the overall overage is above our 90% threshold.

**Comment by johnjbarton** [comment]
So suggest that to karma-threshold-reporter.  Or write your own, it's not a big deal.
