### ISSUE TITLE
Support for <reference ..> tags in comments (IntelliSense support)

### ISSUE THREAD

**Issue by olostan** [karma-runner/karma#675]
I have a lot of tests running by [Chutzpah](http://chutzpah.codeplex.com/).

To reference other scripts, it uses a "reference" tag in comments. So my tests scripts looks like

``` javascript
///<reference path="~/Scripts/jasmine.js"/> 
///<reference path="../../Scripts/jquery-1.8.2.js"/>
///<reference path="../../Scripts/angular.js"/>
///<reference path="../../../Web.Client/Activities/Articles/articlesService.js"/>

'use strict';
describe('Articles Service ', function () {
    var $httpBackend;
    var apiHelper;
....
});
```

([a link to reference](http://blogs.msdn.com/b/webdev/archive/2007/11/06/jscript-intellisense-a-reference-for-the-reference-tag.aspx) about this style of referencing files)

Of course, when I've tried to use Karma for running these tests, there comments were ignores, so no additional files were included.

As a workaround I've put small JS code after defining `files`: 

``` javascript
var refRe = /\/\/\/\s*<reference path=["'](.*?)['"]/g;
var includedFiles = [];
files.forEach(function(f) {
  var sfiles = require('glob').sync(f);
  sfiles.forEach(function(f) {
    var file = require('fs').readFileSync(f);
    var paths = f.split('/');
    var skip = paths.length-1;
    var matches;
    while ((matches = refRe.exec(file))!=null) {
        var refFile = matches[1];

    refFile = refFile.replace(new RegExp('^(\.\./){'+skip+'}'),'');
    if (refFile.indexOf('jasmine')==-1 && includedFiles.indexOf(refFile)==-1) {
        includedFiles.push(refFile);
    }

    };
    includedFiles.push(f);
  });
});
files = includedFiles;
```

So I think it would be a very good addition to Karma to be able to parse there references without adding JS code.  So it could be

``` javascript
files = [
....
   {pattern: 'tests/**/*.js', references: true}
]
```

**Comment by PxlBuzzard** [comment]
Not to dig up an old issue, but I'm also looking to move off of Chutzpah to Karma and ran into this problem as well. I found [karma-reference](https://github.com/vegayours/karma-reference) that seems to replicate the functionality used by Chutzpah, though it involves some find+replace work. However, I like that it uses the [JSDoc](http://usejsdoc.org/), so I think the refactor is worth it.

I haven't completed the migration yet because there are still some problems (the 260 file length limit in Visual Studio, for example). Once I get it up and running I would like to write a blog post, and if I do I'll make sure to link it here.
