### ISSUE TITLE
cant get phantom to run coverage tests (firefox/chrome seem fine)

### ISSUE THREAD

**Issue by peter-mouland** [karma-runner/karma#892]
I have created a small project which demonstrates my problem.

https://github.com/peter-mouland/boilerplate-mocha-with-coverage

The idea of this project is to build a more realistic project structure than the some of the examples i have seen. i.e. config files in a test dir rather than root and specs in a separate dir than the core files etc.  This has meant that i've not been able to get the baseURLs to match each other.

Currently, the phantom report says '0 tests', but I am able to get a full report if i change the preprocessors to:

```
    preprocessors: { '**/*.js': ['coverage'] },
```

This isnt great as node_modules gets processed etc.

any ideas?

**Comment by Alendorff** [comment]
Hello there from 2018. 

Sorry for archeology, but I have just migrated from phantomjs to [puppeteer](https://github.com/GoogleChrome/puppeteer) and faced with that issue. I work with webstorm and usualy it happens when I run single test suite. WS then show me this message as below and doesn't show coverage info to me. Absolutely random thing. Sometimes I get coverage, sometimes - not. 

![image](https://user-images.githubusercontent.com/4989157/35227325-7c8a8fda-ff96-11e7-873f-38bfe41d344f.png)


```
    "grunt-karma": "^2.0.0",
    "jasmine-core": "^2.8.0",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^1.0.1",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.1.1",
    "puppeteer": "^0.13.0"
```
